import {
    CDP_DEFAULT_PORT,
    CDP_DEFAULT_HOST,
    CDP_DEFAULT_URL,
    CDP_CONNECTION_TIMEOUT_MS,
    WINDOW_WAIT_TIMEOUT_MS,
    WINDOW_POLL_INTERVAL_MS,
    NAVIGATION_TIMEOUT_MS,
    ELEMENT_WAIT_TIMEOUT_MS,
    HIGHLIGHT_DURATION_MS,
    SCROLL_AMOUNT_PX,
    AGENT_VIEW_WIDTH,
    AGENT_VIEW_HEIGHT,
} from '@shared/defaults';

export const CDP_CONSTANTS = {
    DEFAULT_PORT: CDP_DEFAULT_PORT,
    DEFAULT_HOST: CDP_DEFAULT_HOST,
    DEFAULT_URL: CDP_DEFAULT_URL,
    CONNECTION_TIMEOUT_MS: CDP_CONNECTION_TIMEOUT_MS,
    WINDOW_WAIT_TIMEOUT_MS: WINDOW_WAIT_TIMEOUT_MS,
    WINDOW_POLL_INTERVAL_MS: WINDOW_POLL_INTERVAL_MS,
} as const;

export const TOOL_TIMEOUTS = {
    NAVIGATION_MS: NAVIGATION_TIMEOUT_MS,
    ELEMENT_WAIT_MS: ELEMENT_WAIT_TIMEOUT_MS,
    HIGHLIGHT_DURATION_MS: HIGHLIGHT_DURATION_MS,
} as const;

export const SCROLL_CONSTANTS = {
    AMOUNT_PX: SCROLL_AMOUNT_PX,
} as const;

export const AGENT_VIEW_CONFIG = {
    DEFAULT_WIDTH: AGENT_VIEW_WIDTH,
    DEFAULT_HEIGHT: AGENT_VIEW_HEIGHT,
} as const;
