export const OBSERVATION_RING_MAX_FRAMES = 200;
export const OBSERVATION_RING_MAX_BYTES = 50 * 1024 * 1024;

export const OBSERVATION_FPS_LONG_WAIT = 0.2;
export const OBSERVATION_FPS_QUICK_ACTION = 10;
export const OBSERVATION_FPS_HIGH_FIDELITY = 30;
